---
apiVersion: hive.kubedoop.dev/v1alpha1
kind: HiveMetastore
metadata:
  name: simple-hive-derby
spec:
  image:
    productVersion: 4.0.1
    kubedoopVersion: 0.0.0-dev
  clusterConfig:
    database:
      connectionString: jdbc:derby:;databaseName=/tmp/hive;create=true
      credentialsSecret: hive-credentials
      databaseType: derby
  metastore:
    roleGroups:
      default:
        replicas: 1
        config:
          resources:
            cpu:
              min: 300m
              max: "2"
            memory:
              limit: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-credentials
type: Opaque
stringData:
  username: APP
  password: mine
